project:
  type: website

website:
  title: "Linn's Data Visualization Projects"
  navbar:
    left:
    - text: "Hands_On Exercises"
      menu:
       - text: "Hands_On_Ex_01"
         href: "Hands_On_Ex/Hands_On_Ex01/Hands_On_Ex01.html"
       - text: "Hands_On_Ex_02"
         href: "Hands_On_Ex/Hands_On_Ex02/Hands_On_Ex_02.html"
       - text: "Hands_On_Ex_03"
         href: "Hands_On_Ex/Hands_On_Ex03/Hands_On_Ex_03.html" 
       - text: "Hands_On_Ex_04"
         href: "Hands_On_Ex/Hands_On_Ex04/Hands_On_Ex_04.html"
       - text: "Hands_On_Ex_05"
         href: "Hands_On_Ex/Hands_On_Ex05/Hands_On_Ex_05.html"
    - text: "In Class Exercises"
      menu:
       - text: "InClass_Ex_01"
         href: "InClass_Ex/InClass_Ex_01/InClass_Ex_01.html"
       - text: "InClass_Ex_04"
         href: "InClass_Ex/InClass_Ex_04/InClass_Ex_04.html"
       - text: "InClass_Ex_05"
         href: "InClass_Ex/InClass_Ex_05/MC1.html"  
    - text: "Take Home Exercises"
      menu:
       - text: "TakeHome_Ex_01"
         href: "Take_Home_Exercise/Take_Home_EX_01/Take_Home_Ex01.html"
       - text: "TakeHome_Ex_02"
         href: "Take_Home_Exercise/Take_Home_EX_02_1/Take_Home_Ex02_1.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

