---
title: "In Class Exercise 02"
execute: 
 eval: true
 echo: true
 warning: false
---

## Loading Tidyverse

```{r}
pacman ::p_load(tidyverse)
```

## Importing Data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

## Working With Theme

```{r}
ggplot(data=exam_data, aes(x=RACE)) +
  geom_bar() +
  coord_flip() +
  theme_minimal() +
  theme(
    panel.background = element_rect(fill = "lightblue", colour = "lightblue", 
                                    size = 0.5, linetype = "solid"),
    panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "white"), 
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "white"))
```

## Making Over Design - Bar Graph

```{r}
ggplot(data=exam_data, 
       aes(x=reorder(RACE,RACE,
                     function(x)-length(x)))) +
  geom_bar() +
  ylim(0,220) +
  geom_text(stat="count", 
      aes(label=paste0(..count.., ", ", 
      round(..count../sum(..count..)*100, 1), "%")),vjust=-1)+ xlab('RACE')+ylab('No of Pupils')+theme(axis.title.y=element_text(angle = 0))
```

```{r}
exam_data %>%
  mutate(RACE = fct_infreq(RACE)) %>%
  ggplot(aes(x = RACE)) + 
  geom_bar()+
  ylim(0,220) +
  geom_text(stat="count", 
      aes(label=paste0(..count.., ", ", 
      round(..count../sum(..count..)*100,
            1), "%")),
      vjust=-1) +
  xlab("Race") +
  ylab("No. of\nPupils") +
  theme(axis.title.y=element_text(angle = 0))
```

## Making Over Design - Histogram (I)

```{r}
ggplot(data=exam_data,
       aes(x=MATHS)) +
  geom_histogram(bins = 20, color = 'black', fill = 'lightblue')+
  geom_vline(aes(xintercept=mean(MATHS,na.rm=T)),color='red',linetype='dashed',size=1) +
  geom_vline(aes(xintercept=median(MATHS,na.rm=T)),color='blue',linetype='dashed',size=1)

```

## Making Over Design - Histogram (II)

```{r}
d <- exam_data   
d_bg <- d[, -3] 
ggplot(d, aes(x = ENGLISH, fill = GENDER)) +
  geom_histogram(data=d_bg,fill='grey',alpha=.5)+
    facet_wrap(~ GENDER)+
  geom_histogram(color='grey30')+
    guides(fill = FALSE)+
  theme_bw()
```

## Making Over Design - Scatterplot

```{r}
ggplot(data=exam_data,
       aes(x=MATHS,y=ENGLISH)) +
  geom_point()+
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  geom_hline(yintercept=50,
             linetype='dashed',
             color='darkblue',
             size=1) +
  geom_vline(xintercept=50,
             linetype='dashed',
             color='darkblue',
             size=1)
```
